### ISSUE TITLE
Hierarchial contiguous arrays

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/range#11]
This is an efficient way of packing hierarchical data. Instead of pointing to another structure through a reference, a range is used to point to all the children. This method is also fast for iterating through all objects at the bottom level. Theoretically, the structure can be passed to GPU memory without loosing its parent/child relations.

For example, a street has a range of houses. When loading a street, the houses are added sequentially to the house array and a new range is added to the street array. When loading a town, a the streets are added sequentially to the street array and a new range is added to the town array. By repeating this process, we get a hierarchy:

```
town (range of streets)
    |- street (range of houses)
        |- house
```

When you have 3 levels of hierarchy, then the third level can emulate arbitrary sets of the first level. For example, a town is an arbitrary set of houses. This is very useful for content management, because you can have different versions of the same town, where many of the houses are shared.

For example, Alice copies a town by copying a range of streets, and then she want to add a new street without affecting the original town. An algorithm copies all the streets, puts it at the end of the street array, and then updates the town to point to the new streets. All streets must be copied because they need to be stored sequentially. While this looks as wasting memory at first, the houses are still shared between the towns. When Alice adds a new house to a new street, the old town is not affected.

Since ranges are used, one can reserve memory for changes within the array. For example, to allow new streets to be added to a town, empty arrays can be inserted at the end of each street range.

**Comment by bvssvni** [comment]
"intersect" and "difference" can be performed on ranges because the result is a subset of either input.

**Comment by kvark** [comment]
This is a nice explanation, thanks for the writeup!
